# Generated by Django 6.0.6 on 2026-06-26 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='clothes/')),
                ('price', models.IntegerField()),
                ('bonus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='outfits/')),
            ],
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='toys/')),
                ('price', models.IntegerField()),
                ('bonus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('last_petted_date', models.DateTimeField(blank=True, null=True)),
                ('current_clothing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_clothing_for_cats', to='generator.clothing')),
                ('wardrobe', models.ManyToManyField(blank=True, related_name='cats_with_wardrobe', to='generator.clothing')),
                ('current_outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.outfit')),
                ('current_toy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_toy_for_cats', to='generator.toy')),
                ('inventory', models.ManyToManyField(blank=True, related_name='cats_with_inventory', to='generator.toy')),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(default=0)),
                ('cat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generator.cat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('weather', models.CharField(choices=[('Sunny', 'Солнечно'), ('Rainy', 'Дождливо'), ('Snowy', 'Снег'), ('Cloudy', 'Облачно'), ('Storm', 'Гроза'), ('Foggy', 'Туманно'), ('Windy', 'Ветренно'), ('Any', 'Любая')], max_length=20)),
                ('temperature', models.IntegerField()),
                ('time', models.CharField(choices=[('Morning', 'Утро'), ('Day', 'День'), ('Evening', 'Вечер'), ('Night', 'Ночь'), ('Any', 'Любое')], max_length=20)),
                ('budget', models.IntegerField()),
                ('mood', models.CharField(choices=[('Bad', 'Плохое'), ('Normal', 'Нормальное'), ('Good', 'Хорошее'), ('Great', 'Отличное'), ('Perfect', 'Замечательное')], max_length=20)),
                ('image', models.ImageField(upload_to='ideas/')),
                ('is_checked', models.BooleanField(default=False)),
                ('pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.pair')),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dates/')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.idea')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.pair')),
            ],
        ),
    ]
