# Generated by Django 6.0.6 on 2026-06-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='name',
            field=models.CharField(default='Микки', max_length=100),
        ),
    ]
