# Generated by Django 6.0.6 on 2026-06-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_remove_pair_user_pair_user1_pair_user2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
