# Generated by Django 6.0.6 on 2026-07-20 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_alter_idea_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='current_clothing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_clothing_for_cats', to='generator.clothing'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='current_toy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_toy_for_cats', to='generator.toy'),
        ),
    ]
